title: JordanaNog Dev
email: jordanasnogueira@gmail.com
description: >-
  Portifólio
baseurl: ""
url: "http://localhost:4000"
twitter_username: JoHh25
github_username:  JordanaNog

include: ['_pages']
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
